server:
  port: ${RESOURCE_PROCESSOR_SERVICE_PORT}

spring:
  application:
    name: ${PROCESSOR_SERVICE_NAME}
  datasource:
    #    url: jdbc:postgresql://host.docker.internal:5432/music_resource
    #    url: jdbc:postgresql://localhost:5432/music_resource
    url: jdbc:postgresql://${DB_SERVICE_HOST}:${DB_SERVICE_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  hibernate:
    ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    ssl:
      enabled: true
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

rabbitmq:
  queue:
    name: music_queue

client:
  services:
    song:
      endpoint: http://${SONG_SERVICE_NAME}/api/v1/songs
    resource:
      endpoint: http://${RESOURCE_SERVICE_NAME}/api/v1/resources/{resourceId}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_REGISTRY_URI:http://localhost:8761/eureka}


management.endpoints.web.exposure.include: '*'
